# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocaleumCli < Formula
  desc "Localeum CLI"
  homepage "https://docs.localeum.com/cli"
  version "1.0.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/localeum/localeum-cli/releases/download/v1.0.5/localeum-cli_Darwin_x86_64.tar.gz"
    sha256 "da75969d7f5e4c05c4ca1d31d45650172dc548cf3dada317d65ab0ba495b1bd1"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/localeum/localeum-cli/releases/download/v1.0.5/localeum-cli_Darwin_arm64.tar.gz"
    sha256 "69a9f07c0015fb736e8415769fdffa46e58cdcab804d295ec94f403de90e12d7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/localeum/localeum-cli/releases/download/v1.0.5/localeum-cli_Linux_x86_64.tar.gz"
    sha256 "f8dc3dce6f1d155f75a5c63ad6b58ca32ef664fe94f5bd0c58264569f45ae32c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/localeum/localeum-cli/releases/download/v1.0.5/localeum-cli_Linux_arm_v6.tar.gz"
    sha256 "a0115c4febfdc412d3764fa2cc513bc10e60ae6ea98e00a9c05f820c0246b9b0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/localeum/localeum-cli/releases/download/v1.0.5/localeum-cli_Linux_arm64.tar.gz"
    sha256 "d32376bf09903218b2b188888afab34c2fb62dd5664be7f8ebfef8342a317876"
  end

  def install
    bin.install "localeum-cli"
  end
end
